enum ErrorCode {
    NOT_FOUND = "NOT_FOUND",
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    DATABASE_ERROR = "DATABASE_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
}

export default ErrorCode;
